- src/main.rs
This translates a few panic points (unwrapping and unchecked indexing)
into normal error bubbling.
> main: get rid of few panic points

- .github/workflows/ci.yml
- src/main.rs
Signed-off-by: Igor Raits <ignatenkobrain@fedoraproject.org>
> Add GitHub CI

- Makefile
- README.md
- TODO
> Create simple makefile to simplify installation procedure

- src/setup.rs
> Use systemd-makefs instead of mkswap

- Cargo.toml
- LICENSE
- README.md
- TODO
- src/config.rs
- src/generator.rs
- src/kernlog.rs
- src/main.rs
- src/setup.rs
> Pull in kernlog and use it for logging

- man/zram-generator.conf.md
- src/config.rs
- src/generator.rs
- tests/04-dropins/etc/systemd/zram-generator.conf.d/04-drop4.conf
- tests/04-dropins/run.expected/units/dev-zram2.swap
> Allow swap priority to be configured

- Cargo.toml
- src/generator.rs
> Version 0.3.0 rc.1

- src/generator.rs
- tests/test_cases.rs
While some distros like Ubuntu 20.10 are found to automatically load `zstd` or related modules when required for `zram-generator` to work, others like Fedora 33 do not mimic this behaviour. I am not sure what prevents or enables that difference in distro configuration, but we can detect if the compressor module is not loaded and attempt to load within `zram-generator`.
The fix queries `/proc/crypto` and parses it to build a list of enabled kernel crypto modules, some of which are of the `compression` type which `zram` uses. The `compression-algorithm` values from config file are collected and checked if they are present in this list, if not, `modprobe <compressor>` is called to load the relevant module.
---
A commit in [this PR](https://github.com/systemd/zram-generator/pull/56#issuecommen …
> fix: Load kernel module for compressors when required

- man/zram-generator.conf.md
Let's see if the branch renaming thingy works.
> man: add note that contents are temporary

- src/generator.rs
The tests failed in Fedora mock build, without modprobe installed.
We don't fail if the modprobe call fails, so we also shouldn't if the
command is unavailable.
> generator: do not fail if modprobe is not found

- src/main.rs
This makes the code prettier but it could be seen as a regression.
> remove utf-8 env validator

- .github/workflows/ci.yml
- Makefile
Supersedes and includes #128 – with ?= at the front, rebased, and override := in the middle.
> More make shenanigans (redux)

- tests/test_cases.rs
Chroots don't allow CLONE_NEWUSER. We need to privatise all mount-points as-if by `mount --make-rprivate /` (unshare(1) already does this by default) to prevent our new `/proc` leaking when running as true root.
Tested as normal user and root-in-chroot.
> Allow tests in chroots

- Makefile
@paulmenzel try this on for size
> Accept NOMAN in Makefile, disabling build: and install: manpage processing

- tests/test_cases.rs
Supersedes #138 – this is my suggested edit from the comment, and warning- + rustfmt-clean.
I'm still curious where you've run into this.
> Skip test if unshare fails (redux)

- src/setup.rs
> Issue warning if /s/b/z0/backing_dev doesn't exist and wb-dev= set

- .github/workflows/ci.yml
This method will reduce failed downloads of this package
> cache: linux-modules-extra

- .github/workflows/ci.yml
in directory /lib/modules/5.15.0-1042-azure
> fixup: modprobe: FATAL: Module zram not found

- .github/workflows/ci.yml
as  ubuntu-24.04 produce errors on test_cases
> ci.yml: use  ubuntu-22.04

- src/config.rs
- src/generator.rs
- src/setup.rs
> fixup: clippy errors
