systemd/zram-generator

Cargo.toml
README.md
TODO
src/main.rs

Rust 2018 + failure → anyhow + misc fixes

---

Cargo.toml

Even though tests are not working in some build environments (like Fedora), it would be still good to ship a new version ASAP so that people can test it.
We will fix the issue in release.

Bump min version of anyhow & bump version to 0.2.0-beta.1

---

.github/workflows/ci.yml
Makefile
README.md
src/setup.rs
units/swap-create@.service.in

This is a fix for the installation problems on Debain, #40. (Or not just Debian, probably all non-merged-/usr distributions are affected?)
----
Add pkg-config calls to the Makefile.
Use an environment variable to pass the location of systemd-makefs to
the Rust code. This gets evaluated at compile-time. If the env var is
unset (e.g. when cargo is invoked by hand), a default is used.
The unit file also needs to be edited before installation.

Use pkg-config for systemd directories

---

Cargo.toml
src/kernlog.rs

`std::process::id()` was added in rust 1.26.
I'm a bit unsure on the formatting, is it preferable to `use std::process` and then `process::id()` or is that wrong cause it imports unnecessary code into the namespace?

Replace libc::getpid with std::process::id

---

.gitignore
Makefile

And also add generated unit to gitignore
Handy for packaging, when the cargo stuff is already handled outside of the Makefile

make: split systemd_service target out of build

---

src/config.rs

It's (a) consistent with `config::read_all_devices()` and (b) prevents confusing errors like in #44

Consistently filter out disabled devices in `config::read_device()`

---

README.md

Recent change modified the `Makefile`, but did not perform a clean build test which would show failure from `make install` advice in the README instructions to build from source. `make build` is also required now.
```
$ make install
```

fix: Install from source split out `build`

---

src/generator.rs

Generators are called on every daemon-reload, and shouldn't log
anything by default.
Also reword the message a bit to emphasize that it's just a config
file that is being created.
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1930869.

Downgrade level of log entries about routine events

---

Cargo.toml

Already merged downstream in Fedora. Does not require code changes (no relevant API changes between 0.16 and 0.17).

allow building against rust-ini 0.17

---

man/zram-generator.md

I missed those somehow in 5502a7ecd90f2fb68f710ca06a7a1ad56cb4590c.
Fixes #80.

man: fix template name

---

.github/workflows/ci.yml

GitHub Actions is now broken due to missing zram kernel module, therefore modprobe failed.
This PR install `linux-modules-extra-$(uname -r)` so auto detect running kernel version and install corresponding required kernel modules correctly.
Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

.github/workflows/ci.yml: Install linux-modules-extra

---

Cargo.toml

Refer to <https://github.com/nabijaczleweli/systemd-zram-generator.deb/commit/8f2f3faf7f1334cfa5ba29352bacada25beeba5a>, building package on Debian 10+ and Ubuntu 20.04+ will fail with `lto = true`.
Moreover, tested with <https://build.opensuse.org/package/show/home:alvistack:systemd/zram-generator>, `lto = "thin"` working well for all support OS, including CentOS/Fedora/Debian/Ubuntu/openSUSE.
Signed-off-by: Wong Hoi Sing Edison <hswong3i@pantarei-design.com>

Cargo.toml: lto = "thin"

---

.github/workflows/ci.yml
Makefile

'make && make install' did not work because the man page wasn't listed
in dependencies. Let's redo the whole scheme:
'make build' builds everything,
'make program', 'make man', 'make systemd-service' build each of
the three items, and 'make install' should now always work.
"systemd_service" is renamed to "systemd-service". Dashes are normally
used in Makefile target names, no need to bother with underscores.
Fixes #82.

make: rework targets

---

src/generator.rs
tests/07-mount-point/run.expected/units/var-compressed.mount

> /run/systemd/generator/var-tmp.mount:11: Where= path is not absolute, ignoring: "/var/tmp"
I think this is should also be fixed in systemd: it should unquote
Where=. But even if that is changed there, we still need to support current
systemd, so also need to fix it here.
Fixes #75.

generator: drop quotes in Where=

---

tests/test_cases.rs

(and spell `&devices[0]` `&devices[0]`)
The test output with a removed 07a directory is such now, which is a far cry from actually saying `test test_07a_mount_point_excl ... skipped`, but is actually noted at least:
```
nabijaczleweli@tarta:~/code/systemd-zram-generator$ SYSTEMD_UTIL_DIR=$(pkg-config --variable=systemdutildir systemd) cargo test --release
Compiling zram-generator v1.0.1 (/home/nabijaczleweli/code/systemd-zram-generator)
Finished release [optimized] target(s) in 1.75s
Running unittests (target/release/deps/zram_generator-d1b62b1787f2545a)
running 7 tests
test config::tests::test_get_total_memory_kb ... ok
test generator::tests::test_mount_unit_name ... ok
test config::tests::test_kernel_has_no_option ... ok
test config::tests::test_verify_mount_point ... ok
test …
```

Only print diff(1) output if not empty

---

.github/workflows/ci.yml
src/config.rs
src/generator.rs

Cf. this hidden failure, for example: https://github.com/systemd/zram-generator/runs/4083411091?check_suite_focus=true#step:4:81
We haven't been running clippy since we started to require `$SYSTEMD_UTIL_DIR` – ff4fb9b51e256b6543485be59d6ec5cdf7228739
~~#124 is clippy-clean, too, so these can be merged independently~~ Conflicts with #124, this needs to go first

Actually run kloppy, fix it

---

Cargo.toml

Fat LTO works on bullseye amd64 and i386, sid amd64, i386, and x32, and focal amd64 (I haven't managed to strap impish, something about base-files being SNAFUd or whatever)
Sizing is quite significant in apparent (250k), and still quite good in real (40k):
```
nabijaczleweli@tarta:~/code/systemd-zram-generator$ l thin true 
-rwxr-xr-x 1 nabijaczleweli users 903K Nov 16 20:21 thin
-rwxr-xr-x 1 nabijaczleweli users 759K Nov 16 20:23 true
nabijaczleweli@tarta:~/code/systemd-zram-generator$ du -h thin true 
441K    thin
405K    true
nabijaczleweli@tarta:~/code/systemd-zram-generator$ size thin true 
text    data     bss     dec     hex filename
868823   45361     776  914960   df610 thin
735002   31137     776  766915   bb3c3 true
```
This reverts PR #93.

Revert "Cargo.toml: lto = "thin"" to = true

---

Cargo.toml

0.22 works too, and Fedora has 0.22, so let's allow that too.

Cargo.toml: relax nix version

---

Cargo.toml
README.md

I woulda included this in some other PR but I only noticed this now when reading my debian package and I don't seem to have any other ones rn, so
Also, the literal `name address@domain` looks weird unstructured – update it to use the classic `name <address@domain>` formatting.

Update my author mail, add Aqs around README mails

---

Cargo.toml

Bump minimum rust-ini to 0.15, first one with ordered keys

---

README.md

NOBUILD=true is necessary if sudo does not have cargo in its PATH, which is quite common.

Update install from source instruction

---

README.md

Include a link to the recently published puppet-zram-generator
https://github.com/voxpupuli/puppet-zram_generator
Mostly just letting you know - will not be sad if not merged.

Include link to puppet-zram_generator

---

src/config.rs
src/generator.rs
src/setup.rs

error: could not compile zram-generator due to 4 previous errors.
This PR will fix this in rust 1.65.0

[Clippy] fixup: the borrowed expression implements the required traits

---

Cargo.toml
src/config.rs

edition=2021 required for `[].into_iter()` actually moving
This reduces needless allocations greatly :)

Use liboverdrop 0.1.0

---

.github/workflows/ci.yml

actions-rs/toolchain@v1 not updated to node 16.
Fixed:

CI: refactor because node 12 will be dropped soon

---

src/generator.rs

consider removing `.into_iter()`

Fixup: useless conversion to the same type: `std::str::Lines<'_>`

---

Cargo.toml

The old version generates warnings about future incompatibility.

Cargo.toml: bump fs_extra version to 1.3

---

man/zram-generator.conf.md
src/config.rs
src/generator.rs
src/setup.rs
tests/09-zram-size/etc/systemd/zram-generator.conf
tests/test_cases.rs
zram-generator.conf.example

Ref: https://github.com/systemd/zram-generator/issues/178#issuecomment-2361314574
I've tested the error case, @OmegaSquad82 needs to test the "actually setting it" case.
A config like
```
compression-algorithm = a b c
```
was previously "compress with `a b c`" (naturally invalid) and is now "compress with `a`, recompress with `b` then `c`"

Allow multiple whitespace-separated compression-algorithm=s, and give the ones after the first one to /recomp_algorithm

---

man/index.txt
man/zram-generator.conf.md
src/config.rs
tests/02-zstd/etc/systemd/zram-generator.conf
tests/10-example/bin/xenstore-read
tests/test_cases.rs
zram-generator.conf.example

Rebased version of #203 with tests added.

Allow "set!var = program" at top level that makes var = eval(system(program))

---

src/generator.rs
tests/01-basic/run.expected/units/dev-zram0.swap
tests/02-zstd/run.expected/units/dev-zram0.swap
tests/04-dropins/run.expected/units/dev-zram0.swap
tests/04-dropins/run.expected/units/dev-zram2.swap
tests/06-kernel-enabled/run.expected/units/dev-zram0.swap
tests/09-zram-size/run.expected/units/dev-zram0.swap
tests/10-example/run.expected/units/dev-zram0.swap
tests/11-obsolete/run.expected/units/dev-zram0.swap
tests/11-obsolete/run.expected/units/dev-zram1.swap

Swap units have automatic dependencies of Before=swap.target,shutdown.target, Conflicts=shutdown.target. By adding DefaultDependencies=no, Before=swap.target, we effective drop the negative dependency with shutdown.target and allow the swap device to survive shutdown.
There is no need to bring down the swap device during shutdown. This wastes work, because any remaning pages need to be dropped or decompressed and moved to normal memory. Normally this is very quick, but the report says that it takes 15–20 seconds in their case.
Closes https://github.com/systemd/zram-generator/issues/191.

Let the swap unit remain survive shutdown

---

Cargo.toml

Current is 0.2.9. The previous version conflicts with the newest clap in:
cargo check --features clap/deprecated
With this update, the check can be run and returns no warnigns.

Cargo.toml: update ctor version

---

Cargo.toml
src/main.rs

Drop indoc dependency and improve style

---

Cargo.toml

This is what Fedora has. Seems to compile just fine.

Cargo.toml: allow rust-ini 0.18

---

src/config.rs

Kernel docs talks about expected ratio of 2:1, use that as a threshold for warning.
Link: https://lists.freedesktop.org/archives/systemd-devel/2024-November/050873.html

config: Add warning for possibly misunderstood disk sizes

---

README.md

The `systemd-zram-generator` package is available in the official Debian repos as of Debian 12 (Bookworm). This should be the preferred installation source for Debian 12 or later.
https://packages.debian.org/search?keywords=systemd-zram-generator

Update Debian installation instructions for Bookworm.

---

README.md

Replaces typo `.` with `-` in the `X-mount.{owner,group}=` documentation.
See
- https://www.kernel.org/pub/linux/utils/util-linux/v2.39/v2.39-ReleaseNotes
- https://github.com/util-linux/util-linux/commit/722c96974dd4009a334e4aee556eedaab5fb94b4
- https://github.com/systemd/zram-generator/commit/1c0aa9cf1fa96e044244059038d0b4d26c1afacd

Fix X-mount README.md typo
